# Installing the required libraries

In [1]:
pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\moham\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\moham\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\moham\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [11]:
from sqlalchemy import create_engine
import pandas as pd

In [4]:
pip install SQLAlchemy pandas pymysql

Requirement already satisfied: SQLAlchemy in c:\users\moham\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pandas in c:\users\moham\anaconda3\lib\site-packages (2.2.3)
Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\moham\anaconda3\lib\site-packages (from SQLAlchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\moham\anaconda3\lib\site-packages (from SQLAlchemy) (4.12.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\moham\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\moham\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\moham\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\moham\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\moham\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2
Note: you may need to restart the kernel to use updated packages.

In [42]:
engine = create_engine("mysql+pymysql://root:Arman9700*@localhost:3306/ecommerce_db")

In [31]:
#engine = create_engine("mysql+pymysql://root:Arman9700*@localhost:3306/amazon")

In [32]:
#running other database queries just to check whether its working properly 

q1="""select*from master_cleaned_data"""

In [33]:
df1=pd.read_sql(q1,engine)
df1

,order_id,order_date,product_name,price,quantity,status,total_revenue,customer_id,name,city
0,ORD2001,2024-10-01,Laptop,55000.0,1,Delivered,55000.0,1001,Anil Kumar,hyderabad
1,ORD2002,2024-10-01,Mouse,1200.0,2,Shipped,2400.0,1002,Sunita Reddy,mumbai
2,ORD2003,2024-10-02,Keyboard,2500.0,1,Delivered,2500.0,1003,Rohan Gupta,bangalore
3,ORD2004,2024-10-03,Headphones,3000.0,1,Delivered,3000.0,1001,Anil Kumar,hyderabad
4,ORD2006,2024-10-04,External HDD,4500.0,1,Shipped,4500.0,1002,Sunita Reddy,mumbai
5,ORD2007,2024-10-04,Monitor,12000.0,2,Delivered,24000.0,1005,Amit Singh,mumbai
6,ORD2009,2024-10-05,Mouse,1200.0,1,Delivered,1200.0,1001,Anil Kumar,hyderabad
7,ORD2011,2024-10-06,Monitor,12000.0,1,Shipped,12000.0,1007,Vikram Nair,pune
8,ORD2012,2024-10-06,Headphones,3000.0,2,Delivered,6000.0,1008,Sonia Verma,hyderabad

In [39]:
q2="""
select product_name,sum(total_revenue) as rev from master_cleaned_data
group by product_name
order by sum(total_revenue) desc
"""

In [40]:
df2=pd.read_sql(q2,engine)
df2

   product_name      rev
0        Laptop  55000.0
1       Monitor  36000.0
2    Headphones   9000.0
3  External HDD   4500.0
4         Mouse   3600.0
5      Keyboard   2500.0

In [43]:
pip install mysql-connector-python

Collecting mysql-connector-pythonNote: you may need to restart the kernel to use updated packages.

  Downloading mysql_connector_python-9.5.0-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Downloading mysql_connector_python-9.5.0-cp313-cp313-win_amd64.whl (16.5 MB)
   ---------------------------------------- 0.0/16.5 MB ? eta -:--:--
   ---- ----------------------------------- 1.8/16.5 MB 9.7 MB/s eta 0:00:02
   --------- ------------------------------ 3.9/16.5 MB 10.2 MB/s eta 0:00:02
   --------------- ------------------------ 6.3/16.5 MB 10.4 MB/s eta 0:00:01
   -------------------- ------------------- 8.7/16.5 MB 10.6 MB/s eta 0:00:01
   -------------------------- ------------- 11.0/16.5 MB 10.6 MB/s eta 0:00:01
   -------------------------------- ------- 13.4/16.5 MB 10.6 MB/s eta 0:00:01
   -------------------------------------- - 15.7/16.5 MB 10.6 MB/s eta 0:00:01
   ---------------------------------------- 16.5/16.5 MB 10.1 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.5.0

In [56]:
from sqlalchemy import create_engine
import pandas as pd
import os
import mysql.connector

engine = create_engine("mysql+pymysql://root:Arman9700*@localhost:3306/ecommerce_db")

DATA_PATH = r"C:\Users\moham\Downloads\Data Sets\Data Sets"

#  MySQL connector config
config = {
    'user':'root',
    'password':'Arman9700*',   # Raw password is fine here
    'host':'localhost',
    'database':'ecommerce_db',
    'raise_on_warnings': True
}
#  Connect and insert
conn=None
try:
    conn = mysql.connector.connect(**config)
    cursor = conn.cursor()
    print(" MySQL connection established successfully.")

    csv_files = [
        'olist_customers_dataset.csv',
        'olist_orders_dataset.csv',
        'olist_order_items_dataset.csv',
        'olist_order_payments_dataset.csv',
        'olist_order_reviews_dataset.csv',
        'olist_products_dataset.csv',
        'olist_sellers_dataset.csv',
        'product_category_name_translation.csv'
    ]

    for file in csv_files:
        df = pd.read_csv(os.path.join(DATA_PATH, file))
        table_name = file.replace('.csv', '').replace('olist_', '').replace('_dataset', '')
        df.to_sql(name=table_name, con=engine, if_exists='replace', index=False)
        print(f" Table '{table_name}' created successfully.")
        
except mysql.connector.Error as err:
    print(f" Error: {err}")
finally:
    if conn is not None and conn.is_connected():
        cursor.close()
        conn.close()
        print(" MySQL connection closed.")

 MySQL connection established successfully.
 Table 'customers' created successfully.
 Table 'orders' created successfully.
 Table 'order_items' created successfully.
 Table 'order_payments' created successfully.
 Table 'order_reviews' created successfully.
 Table 'products' created successfully.
 Table 'sellers' created successfully.
 Table 'product_category_name_translation' created successfully.
 MySQL connection closed.